notifications:
  email: false

rvm:
  - 2.3.0

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: false
language: ruby
cache: bundler

jdk:
  - oraclejdk8

before_script:
  - bundle exec rake db:create

before_deploy:
  - git clean -dxf; rm -rf vendor/bundle
  - echo $TRAVIS_COMMIT > REVISION
  - mkdir build; zip -q -r build/hybox.zip .

services:
  - postgresql
  - redis-server

deploy:
  - provider: s3
    access_key_id:
      secure: "VPgy/7mq+jzSDx2cHOQ2M5O8k4Khi7czmXZAVPH2fA87dlnmCpprJkfuekinvMVXyMkCfs6DYfKkJ/dbzPfzIm7N3kxvI6fcfOCR/kuQFW8SAJMUhxLiE4DqXHvU725b5jT6Zc+3WdJBcFzrtBCdf6YorhQCFLVpfc0tCJIS1sPE+a7jZFQvrsaALPZZpOG9jmxZhX9Q0GKnc4xpzwLSv1fVkqT1GEAwmDiboVHdDN0MPh7Lp2L2VpXnuBidMpuXEimW35iVbcCDhbkoBbTnz+jRhQBCAFIsTwNi/BjjibZ7KuuRZQ3s0i0zFnhu/TWyia5jbgr7tcB4Emo5rw5vVRmmYrA79NqImBGDAXcyIrrMOsHxjTPq47ws2KAjGEQ7dQtaw/pQkveY361Uvnib72KZC4Go+FMKYGTxhgLYJXuwBWa0lX+DLfezNcKFkRdH6V8Z/nwkvJi8L+CRfwjiuILch+ABZWgn07t7EQ9wAtscuYAJhdiYrpK4yUd44aWqIkLZHzF78jIaWRu8zdLcFSeA+g67LLBNj6Wa7ZWxMUzcgJh4+KiLN3rGVzUCstTAIFiZYCBWdq270wWjVRkNHy184vt53i4iQxmjRRFLUwmAIFvO1PCjw/4m6gCdrfoABIAdu7b8Gt8B+HEwFCGVn9IghkDkR2rTlVavj36MndA="
    secret_access_key:
      secure: iaeQhv5WMVaxAvVRS3DckUipqNDUyNd+BMPCSn+RttLPDJrzTjjw2WrQiNI1/z0aVfhkItNZ/nkect+IHTidRIgF4ZlD2KQmQvsI3uyHn9SkWqn8jn78UDEnaJ3fJgRoNL2Fiyb29GMoCzaL3jjPoy8XByrtJxk+3NrEtE5SnShr6b/yuFLDXtzZMSvuzM+BF6YZNGkJLhaFGF1Q/Tg3qgST+Oph/0lxZiF9HtqhV+tKw/yFlWOZJhx3JMv+dMWs/LUpetHw8mdXIg21lkpecQ6+vg4OWc7PLrKBSiAssQkb5506E4b42SFOw+1kWZcbyBa6E4KlxO/Yobbh1BCq8dZKk9+xknVI0lptZ6moOKnVMMXCljlaD6acpsQm8hvc2OFxv4agzwZHpNX7mbe8FLtBsK00P8gmFckiMMQQP+SkZJKVgKr4i2doCS7x0WuLIWn21dOZGBKEyLwPuJOcgjMCaC8sg4Q0Vf4uJdvuwwdN9K4Pi8paCKtbGb6RbQF3eA08gnbHdd1BRRSo7bMfx37VQ9ZeuySN5F49fiOIuVgCXawXYKah5KQza0ge510djOhFunBaaIl3uk4Y80lyH9oQoxHIUzf1EseclmJ6tWNJRpSQVM8sctjiKFs+SkCC7azPfvSKtcWHbO3vAuhIWHUSDXLeDo14kYGJHiZ1ReA=
    bucket: hybox-deployment-artifacts
    region: us-east-1
    local_dir: build
    skip_cleanup: true
    upload-dir: hybox/branch/${TRAVIS_BRANCH}
    acl: public_read
    on:
      all_branches: true
  - provider: s3
    access_key_id:
      secure: "VPgy/7mq+jzSDx2cHOQ2M5O8k4Khi7czmXZAVPH2fA87dlnmCpprJkfuekinvMVXyMkCfs6DYfKkJ/dbzPfzIm7N3kxvI6fcfOCR/kuQFW8SAJMUhxLiE4DqXHvU725b5jT6Zc+3WdJBcFzrtBCdf6YorhQCFLVpfc0tCJIS1sPE+a7jZFQvrsaALPZZpOG9jmxZhX9Q0GKnc4xpzwLSv1fVkqT1GEAwmDiboVHdDN0MPh7Lp2L2VpXnuBidMpuXEimW35iVbcCDhbkoBbTnz+jRhQBCAFIsTwNi/BjjibZ7KuuRZQ3s0i0zFnhu/TWyia5jbgr7tcB4Emo5rw5vVRmmYrA79NqImBGDAXcyIrrMOsHxjTPq47ws2KAjGEQ7dQtaw/pQkveY361Uvnib72KZC4Go+FMKYGTxhgLYJXuwBWa0lX+DLfezNcKFkRdH6V8Z/nwkvJi8L+CRfwjiuILch+ABZWgn07t7EQ9wAtscuYAJhdiYrpK4yUd44aWqIkLZHzF78jIaWRu8zdLcFSeA+g67LLBNj6Wa7ZWxMUzcgJh4+KiLN3rGVzUCstTAIFiZYCBWdq270wWjVRkNHy184vt53i4iQxmjRRFLUwmAIFvO1PCjw/4m6gCdrfoABIAdu7b8Gt8B+HEwFCGVn9IghkDkR2rTlVavj36MndA="
    secret_access_key:
      secure: iaeQhv5WMVaxAvVRS3DckUipqNDUyNd+BMPCSn+RttLPDJrzTjjw2WrQiNI1/z0aVfhkItNZ/nkect+IHTidRIgF4ZlD2KQmQvsI3uyHn9SkWqn8jn78UDEnaJ3fJgRoNL2Fiyb29GMoCzaL3jjPoy8XByrtJxk+3NrEtE5SnShr6b/yuFLDXtzZMSvuzM+BF6YZNGkJLhaFGF1Q/Tg3qgST+Oph/0lxZiF9HtqhV+tKw/yFlWOZJhx3JMv+dMWs/LUpetHw8mdXIg21lkpecQ6+vg4OWc7PLrKBSiAssQkb5506E4b42SFOw+1kWZcbyBa6E4KlxO/Yobbh1BCq8dZKk9+xknVI0lptZ6moOKnVMMXCljlaD6acpsQm8hvc2OFxv4agzwZHpNX7mbe8FLtBsK00P8gmFckiMMQQP+SkZJKVgKr4i2doCS7x0WuLIWn21dOZGBKEyLwPuJOcgjMCaC8sg4Q0Vf4uJdvuwwdN9K4Pi8paCKtbGb6RbQF3eA08gnbHdd1BRRSo7bMfx37VQ9ZeuySN5F49fiOIuVgCXawXYKah5KQza0ge510djOhFunBaaIl3uk4Y80lyH9oQoxHIUzf1EseclmJ6tWNJRpSQVM8sctjiKFs+SkCC7azPfvSKtcWHbO3vAuhIWHUSDXLeDo14kYGJHiZ1ReA=
    bucket: hybox-deployment-artifacts
    region: us-east-1
    skip_cleanup: true
    local_dir: build
    upload-dir: hybox/current
    acl: public_read
