---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "hyku.sidekiq.name" . }}
  labels:
    app: {{ template "hyku.name" . }}
    chart: {{ template "hyku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: sidekiq
spec:
  replicas: {{ .Values.sidekiq.replicas }}
  selector:
    matchLabels:
      app: {{ template "hyku.name" . }}
      release: {{ .Release.Name }}
      component: sidekiq
  template:
    metadata:
      labels:
        app: {{ template "hyku.name" . }}
        release: {{ .Release.Name }}
        component: sidekiq
      annotations:
        checksum/rails-env-cm: {{ include (print $.Template.BasePath "/rails-env-cm.yaml") . | sha256sum }}
        checksum/rails-env-secret: {{ include (print $.Template.BasePath "/rails-env-secret.yaml") . | sha256sum }}
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: {{ .Values.sidekiq.timeout | add 5 }}
      {{- if .Values.rails.imagePullSecrets }}
      imagePullSecrets:
        {{ toYaml .Values.rails.imagePullSecrets }}
      {{- end }}
      volumes:
        - name: shared
          persistentVolumeClaim:
            claimName: {{ template "hyku.rails-env.name" . }}-shared
      containers:
        - name: sidekiq
          image: {{ .Values.rails.image.repository }}:{{ .Values.rails.image.tag }}
          imagePullPolicy: Always
          command: ["/bin/bash"]
          args:
            - "-l"
            - "-c"
            - "bundle exec sidekiq"
          # livenessProbe:
          #   exec:
          #     command:
          #       - ./bin/rails runner ./chart/bin/check_sidekiq.rb
          #   initialDelaySeconds: 30
          # Use sub-path for individual folders
          volumeMounts:
            - mountPath: /home/app/webapp/tmp/imports
              name: shared
              subPath: import_path
            - mountPath: /home/app/webapp/tmp/exports
              name: shared
              subPath: export_path
            - mountPath: /home/app/webapp/tmp/derivatives
              name: shared
              subPath: derivatives_path
            - mountPath: /home/app/webapp/tmp/network_files
              name: shared
              subPath: network_files
            - mountPath: /home/app/webapp/tmp/uploads
              name: shared
              subPath: upload_path
            - mountPath: /home/app/webapp/public/uploads
              name: shared
              subPath: uploads
            - mountPath: /home/app/webapp/public/assets
              name: shared
              subPath: assets
            - mountPath: /home/app/webapp/public/branding
              name: shared
              subPath: branding
          envFrom:
            - configMapRef:
                name: {{ template "hyku.rails-env.name" . }}
            - secretRef:
                name: {{ template "hyku.rails-env.name" . }}
