# These settings are to provide information about your theme
# and should follow the format
# default:
#   name: Default theme
#
default_home:
  banner_image: true
  featured_researcher: true
  home_page_text: false
  marketing_text: true
  name: Default home
  notes: This theme is the default Hyku view
cultural_repository:
  banner_image: true
  featured_researcher: false
  home_page_text: true
  marketing_text: true
  name: Cultural Repository
  notes: This theme is recommended for cultural repositories
institutional_repository:
  banner_image: true
  featured_researcher: true
  home_page_text: true
  marketing_text: true
  name: Institutional Repository
  notes: This theme is recommended for institutional repositories
neutral_repository:
  banner_image: true
  featured_researcher: true
  home_page_text: true
  marketing_text: true
  name: Neutral Repository
  notes: This theme is neutral and is recommended for all types of repositories